# Generated by Django 5.1.1 on 2024-10-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_rename_runs_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='json_data',
        ),
        migrations.AddField(
            model_name='run',
            name='input_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='output_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
