# Generated by Django 5.1.1 on 2024-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_remove_run_json_data_run_input_data_run_output_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
