# Generated by Django 5.1.1 on 2024-10-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_run_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
