# Generated by Django 5.1.1 on 2024-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_alter_run_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='model_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
