# Generated by Django 5.1.1 on 2024-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_run_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
